### ISSUE TITLE
Fail to generate icons /splahes with an error :

### ISSUE THREAD

**Issue by v3ss0n** [isleofcode/splicon#13]
```

Error: write EPIPE
    at exports._errnoException (util.js:1007:11)
    at WriteWrap.afterWrite (net.js:793:14)
v3ss@hexcode ~/ondr-mobile/ember-cordova/cordova $ splicon-splashes
Generating cordova splashes for
events.js:160
      throw er; // Unhandled 'error' event
      ^
```
```
Error: write EPIPE
    at exports._errnoException (util.js:1007:11)
    at WriteWrap.afterWrite (net.js:793:14)
```

**Comment by v3ss0n** [comment]
BUMP , still having same error.

**Comment by jordanyee** [comment]
@v3ss0n It looks like you're running `splicon-splashes` from the `ember-cordova/cordova` directory rather than `ember-cordova` which may be the issue.

However is there a reason you're not running `ember cdv:make-splashes` instead as documented in http://embercordova.com/pages/workflow/icon_splash_management ?

Try those two and see if that helps!

**Comment by v3ss0n** [comment]
i tried both ways. Same problem.

**Comment by jordanyee** [comment]
What version of ember-cordova, node, and OS are you using?

**Comment by jordanyee** [comment]
Closing due to inactivity. 

Reopen if this is still an issue 💁‍♂️
