### ISSUE TITLE
It doesn't seem to work on the cli as the readme suggests

### ISSUE THREAD

**Issue by kitsunde** [isleofcode/splicon#8]
I tried doing this:

> Using the cli, from your cordova project, simply run:
>
>```bash
> splicon-icons
>```

Which doesn't seem to work:

```bash
$ npm install  splicon -g
# splicon-icons
module.js:442
    throw err;
    ^

Error: Cannot find module '../lib/icon-task'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/splicon/bin/splicon-icons.js:8:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

I'm on node v6.3.1

**Comment by jordanyee** [comment]
Thanks for the bug report, this should be fixed in [0.0.6](https://github.com/isleofcode/splicon/releases/tag/0.0.6). 

Feel free to reopen if the problem persists.
